<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Platforms>x64</Platforms>
	<ApplicationIcon>Resources\MHAchiev.ico</ApplicationIcon>
	<Configurations>Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Blank.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Blank.png" />
    <EmbeddedResource Include="Resources\MHAchiev.ico" />
    <ProjectReference Include="..\dep\OpenCalligraphy.Core\OpenCalligraphy.Core.csproj" />
    <ProjectReference Include="..\dep\UpkManager\UpkManager.csproj" />
  </ItemGroup>
  
  <Target Name="CopyDlls" AfterTargets="AfterBuild">
    <Copy SourceFiles="..\dep\UpkManager\Compression\lib64\lzo2_64.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="..\dep\UpkManager\Compression\lib64\msvcr100.dll" DestinationFolder="$(OutDir)" />
  </Target>

</Project>
