<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
	<ApplicationIcon>Resources\MHAchiev.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\MHAchiev.ico" />
    <ProjectReference Include="..\OpenCalligraphy.Core\OpenCalligraphy.Core.csproj" />
  </ItemGroup>

</Project>
